# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 561e6c1fa236c9600ff09d688eff101d7f330573447c52c51a7d7b7fa945e1ae4d14d9c5c938904cee61043aa28b1408562dc9efb4401e4b4080ab4b4f38c0e1

test:
  secret_key_base: 84f7f55b87ccfb11f682add2bd73c537d20f00b9111ff131eca7332e1099b5497e503c2923581cb2555eacf59336d441be806184a23703443eaec869731a2b98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
